### ISSUE TITLE
App Crashes On Open Android 13

### ISSUE THREAD

**Issue by DarkCrypt** [Tutislav/neodeemer#1]
V0.5 crashes on open making app unusable, Android 13.

**Comment by DarkCrypt** [comment]
Yes, I allowed all permissions(when app requested and manually) including notifications and v0.5 crashes on startup no matter what I do. I uninstalled and installed v.04 to see if I get the same result and app crashed on startup. I then gave all permissions including notifications manually and now the app works properly.

I tried to update v.04 with in app updater which downloaded update but when I tried to install v0.5 it threw error for conflicting package and wouldn't update. So I uninstalled v0.4 and downloaded v0.5 from releases page and am back to said continuous crashes on startup. I have also cleared data and cache and received no improvement.

**Comment by Tutislav** [comment]
That's weird. Would you mind sharing log from ADB logcat? You can connect your phone to PC by USB and then run ADB logcat in browser from [here](https://app.webadb.com/logcat). You also need to enable [USB debugging](https://www.makeuseof.com/tag/what-is-usb-debugging-mode-on-android-makeuseof-explains/#how-do-i-enable-usb-debugging-on-android) on your phone for this to work.

**Comment by DarkCrypt** [comment]
I got the browser to read log but couldn't figure out how to save and send you log. But I do know how to do logcat with adb and computer so I did that. Hopefully this helps.
[neodeemerv05op9proa13.txt](https://github.com/Tutislav/neodeemer/files/10866455/neodeemerv05op9proa13.txt)

**Comment by Tutislav** [comment]
Thanks for log. It looks like one library i use in this app is crashing it on some devices. I've downgraded it to older version of this library. Could you try this [apk](https://github.com/Tutislav/neodeemer-dev-test/releases/download/0.5-debug/neodeemer_0.5_android_debug.apk) please?

**Comment by DarkCrypt** [comment]
No problem, glad log provided useful information. Debug apk works great.

**Comment by DarkCrypt** [comment]
No problem, glad log showed useful information.

Debug apk opened and is usable but there are a few noticeable issues.

Issues(Android 13):

1. Player crashes frequently when trying to play song. Will do this even after granting notification permission manually. (Player is a much better option than forcing users to go to YouTube or elsewhere)
2. Downloader works but multiple que doesn't seem to like to work. Doesn't want to download more than 1 song. (Downloading speed was fast)

I haven't used the app much yet but this it what I've experienced so far.

**Comment by Tutislav** [comment]
Thanks for help. As for the issues you described, there is a bug in https://github.com/yt-dlp/yt-dlp/issues/6400 which slow down downloading, so I'm still waiting for the fix. Hopefully it also fixes the player, which also relies on yt-dlp.

**Comment by DarkCrypt** [comment]
Grrr, typical Google bs! I really don't like them.

**Comment by DarkCrypt** [comment]
What do you think about using NewPipe Extractor instead of yt-dlp? [Hymn](https://github.com/supersu-man/hymn) did this recently and now music downloads are lightning fast.

**Comment by Tutislav** [comment]
Thanks, I look into it.

**Comment by Cathryn2003** [comment]
i didn't find anyway to contact you so contacting you here
how can i download age restricted song. When downloading this type of song it says "Error while downloading"

**Comment by DarkCrypt** [comment]
> how can i download age restricted song. When downloading this type of song it says "Error while downloading"

Strange, I just downloaded and played an explicit song without issue.

I can try to recreate the issue. What's 1 song that isn't downloading?

**Comment by Cathryn2003** [comment]
https://www.youtube.com/watch?v=IvXivTuyly4

Here it is

**Comment by DarkCrypt** [comment]
> https://www.youtube.com/watch?v=IvXivTuyly4
> 
> Here it is

Cannot recreate, this song downloaded without issue.

**Comment by Cathryn2003** [comment]
ohh yeah it's downloading when i try this time but previous time i was dowloading playlist from there this explicit song got error and other explicit song

**Comment by Cathryn2003** [comment]
also some song downloded have album art some don't have is there any way i can solve

**Comment by DarkCrypt** [comment]
> also some song downloded have album art some don't have is there any way i can solve

This is beyond my knowledge, Tutislav will be able to help you though. Open a new issue and he'll respond when he can.

**Comment by Tutislav** [comment]
> ohh yeah it's downloading when i try this time but previous time i was dowloading playlist from there this explicit song got error and other explicit song

@Cathryn2003 That's weird. Could you please share link to that playlist?
