### ISSUE TITLE
[BUG] Replacement strings in filenames for special characters

### ISSUE THREAD

**Issue by xamionex** [Tutislav/neodeemer#3]
By accident I stumbled upon this
![image](https://github.com/Tutislav/neodeemer/assets/57235791/c8467f54-078c-4f51-a0b4-ab22da43427c)
Which made me think it'd probably tried doing ** in the filename which just removed them ;p
Dunno how'd you avoid this but I was thinking __ or some unicode

**Comment by Tutislav** [comment]
Some characters like * or ? are forbidden in filenames on Windows so I just filtered filename to alphanumerical characters only. Anyway when you play it in any music player, it should display the right name, because it's saved as tag to file.

**Comment by xamionex** [comment]
> Some characters like * or ? are forbidden in filenames on Windows so I just filtered filename to alphanumerical characters only. Anyway when you play it in any music player, it should display the right name, because it's saved as tag to file.

Yeah I know, but it looks really weird without anything replacing it, so I was thinking of just replacing it but your solution makes sense after looking at metadata, you can close if you want
